name: mongo_document
description: A code generator for MongoDB-backed Dart models using @MongoDocument annotations - build type-safe, maintainable backend layers.
version: 1.6.7
repository: https://github.com/wanclem/mongo_document
homepage: https://github.com/wanclem/mongo_document
issue_tracker: https://github.com/wanclem/mongo_document/issues
documentation: https://github.com/wanclem/mongo_document#readme

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  source_gen: ^4.0.2
  build: ^4.0.0
  mongo_document_annotation: ^1.6.7
  mongo_dart: ^0.10.5
  json_annotation: ^4.9.0
  dart_style: ">=2.3.8 <4.0.0"
  path: ^1.9.1
  collection: ^1.19.1
  recase: ^4.1.0
  analyzer: ^8.2.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.10.3
  mockito: ^5.4.6
  build_test: ^3.5.3
  package_config: ^2.2.0
  crypto: ^3.0.6
  glob: ^2.1.3
  _fe_analyzer_shared: ^89.0.0

topics:
  - codegen
  - mongodb
  - backend
  - dart
  - annotations
