name: mongo_document_annotation
description: Generate MongoDB CRUD code in Dart using @MongoDocument annotations â€“ ideal for clean, scalable backend models.
version: 1.2.3
homepage: https://github.com/wanclem/mongo_document
repository: https://github.com/wanclem/mongo_document
issue_tracker: https://github.com/wanclem/mongo_document/issues
documentation: https://github.com/wanclem/mongo_document#readme

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ">=2.4.4 <4.0.0"
  meta: ^1.16.0
  mongo_dart: ^0.10.5
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.0.0
  test: ^1.24.0
  source_gen: ^2.0.0
  freezed: ">=2.5.8 <4.0.0"
  json_serializable: ^6.9.3

topics:
  - mongodb
  - codegen
  - annotations
  - dart
  - backend
