name: example
description: A sample command-line application.
version: 1.6.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  dotenv: ^4.2.0
  mongo_document_annotation: ^1.6.7
  freezed_annotation: ">=2.4.4 <4.0.0"

dev_dependencies:
  freezed: ">=2.5.8 <4.0.0"
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  mongo_document: ^1.6.7
  lints: ^5.0.0
  test: ^1.24.0
